require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
