require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/initializers/simple_form_bootstrap.rb'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Metrics/MethodLength:
  Max: 20

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
