app_name: Scratch Admin

redis_url: redis://localhost:6379/1
devise_secret_key:
devise_pepper_key:

database_username: root
database_password:

production:
  database_username: deploy
  database_password:
